sudo: false
language: node_js

node_js: stable
cache: false

after_failure:
  - python scripts/send_to_bot.py < test_result

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
