sudo: required
language: node_js

node_js:
- stable
cache: false

before_script:
- sudo apt-get install python3-pip
- sudo pip3 install beautifulsoup4
- sudo pip3 install requests
- sudo pip3 install gitpython

after_success:
- bash scripts/build.sh
- python3 scripts/command_coverage.py

after_failure:
- cat test_result | python scripts/send_to_bot.py

env:
  global:
  # Used to upload the tldr archive to tldr-pages repo.
  # Achieved via the upload_assets() function of scripts/build.sh
  # This is an encrypted form of @agnivade's user token.
  - secure: AJPra/q3bCFHzMOam1aFz4tzasYuU261Mk6lISh1VJatibHa7nBErsuA3VbR5qth9LblH5HFmNGl4bwmas/PTD1P3lPAHO19gdlMb1kpS9MhTojQP/0EPCsyMTgnWcmNMU2XMvYGHFT0JFn4vj/0TrM9CUMDoT9WhtnVJfgRrlY=
