sudo: false
language: node_js

node_js: stable
cache: false

git:
  depth: 1

script:
  - npm test
  - bash scripts/build.sh

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    repo: tldr-pages/tldr
    branch: master
