name: Codespell

on: ['pull_request']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40.0.2
        with:
          # Ignore all other languages except English
          files_ignore: |
            pages.*/*/*
            package-lock.json

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - uses: codespell-project/actions-codespell@v2
        with:
          ignore_words_file: .github/codespell-ignore
          # Exit with 0 regardless of typos.
          only_warn: 1
          # Skip non-English pages
          skip: ./pages.*/*/*.md,./contributing-guides/style-guide.*.md
          # Only check files in the PR
          path: ${{ steps.changed-files.outputs.all_changed_files }}
